title: "Altafino Blog"
baseline: "Software Solutions"
description: "Software Solutions & Full-Stack Development"
baseurl: "/"
canonicalurl: true
#theme: "altafino"
date:
  format: "j F Y"
  timezone: "Europe/Paris"
pagination:
  max: 5
  path: "page"
output:
  formats:
    netlify_redirects:
      mediatype: "text/plain"
      extension: ""
virtualpages:
  admin:
    layout: admin/index
    output: html
    title: "Content Manager (Netlify CMS)"
  _redirects:
    output: netlify_redirects
collections:
  - label: "Blog in English"
    name: "english_posts"
    folder: "_posts"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
netlify:
  cms:
    path: "admin"
    version: "latest"
  identity:
    version: "v1"
